name: mc2
dependencies:
- python=3.6

# Bare necessities
- flake8
- cython
- pandas >= 0.25
- jupyterlab

# Optional:
- joblib  # to be able to use crud.main(cache=True)
- fastparquet
- termcolor  # tmux

- pip

- pip:
  - toolz
  - fire
  - pandas-gbq
  # - google-cloud-bigquery
