name: mc2
dependencies:
- python=3.6
# pip install python-box

# Bare necessities
- flake8
- cython
- pandas
- jupyterlab

# Optional:
- joblib  # to be able to use crud.main(cache=True)
- fastparquet

- pip

- pip:
  - toolz
  - fire
  - pandas-gbq
  # - google-cloud-bigquery
