---
title: FAQ
output:
  html_document:
     theme: cosmo
     toc: true
---


```{r relstuff,echo=FALSE}
library(knitr)
library(kableExtra)
knitr::opts_chunk$set(echo=FALSE, warning=FALSE,messages=FALSE)
```

#### What all do you compute and what rates and incidences?

For a given channel and os, we compute 

- *nvc* which is the percentage of the total active hours on the browser coming
  from profiles on the latest version. This is a measure of adoption and good
  proxy for the reliability of any crash statistic. An `nvc` of 40% means 40% of
  the active hours on Firefox came from the newest version. During rollout the
  `nvc` can be tiny (a few percents in the initial few days and varies by OS)
  and during this time, the crash statistics are *very* noisy. As adoption
  increases the noise drops and the statistics become stable and reliable.
  
- *crash incidence* is the percentage  of active profiles on the current version
  that experience a crash (say a browser crash). A value of 0.7% means that 0.7%
  of the profiles active on the current version experienced a crash (say
  browser) on that day. It is often less than a percent. Keep in mind our
  Windows Release DAU on the current version is  in the tens of millions.
  
- *crash rate* is the total number of say browser crashes on the current version
  divided by active hours experienced by those that crashed (*not* including
  profiles that did not crash). Thus a crash rate of 2.3 means that crashing
  profiles experienced on average 2.3 crashes (say browser) per active hour.
  
- For crash incidence and crash rate, we also compute high and low values which
  is a measure of uncertainty.
  
- For the adoption curves we include a value called `regProb` which is the
  probability of regression. A regression is when the relative difference
  between this and previous version exceeds 35%.
  
  
#### Can you explain the different plots?

Absolutely

#### Summary


#### Adoption


#### Trend





